# SabiScore — Improved Serena Project Configuration (v3.1)
# Generated: 2025-11-21
# Maintainer: SabiScore / Oscar Dubu
# Purpose: Production-ready Serena MCP config tuned for Windows dev host.

# ---- Core (required) ------------------------------------------------------
project_root: "C:/Users/USR/Documents/SabiScore"  # Absolute path (Windows-compatible)
active_project: "C:/Users/USR/Documents/SabiScore" # Force this project to be the active project

# Operational modes (influence assistant/system prompts and tool behavior)
modes:
  - "ide-assistant"

# MCP tooling toggles (enable/disable capabilities exposed to the MCP agent)
tools:
  code_search: true
  edit_file: true
  list_files: true
  read_file: true
  test_execution: false   # Keep disabled when tests may mutate important data
  run_command: false      # Keep disabled for security; enable only for trusted local dev

# Indexing configuration (controls how the project is indexed for retrieval)
index:
  enabled: true
  index_on_start: true   # Build/refresh index automatically when MCP server starts
  exclude_patterns:
    - ".git/"
    - "node_modules/"
    - ".next/"
    - "dist/"
    - "__pycache__/"
    - "*.log"
    - "*.db"
    - "cache/"
    - ".turbo/"
    - ".env*"       # avoid seeding secrets into the index
  include_file_globs:
    - "**/*.py"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.md"
  batch_size: 500      # tuneable: reduce if memory pressure

# Language servers for symbol-level features & intelligence
language_servers:
  - "python"
  - "typescript"

# MCP server settings (tunable; useful when running locally or in container)
mcp_server:
  host: "127.0.0.1"
  port: 8000
  enable_tls: false

# Optional: Known projects list (helps CLI/agents present choices)
known_projects:
  - name: "SabiScore"
    path: "C:/Users/USR/Documents/SabiScore"

# Project metadata (informational only)
project:
  name: "SabiScore"
  version: "3.1.0"
  description: "Low-latency sports-betting edge detection platform"
  repository: "https://github.com/Scardubu/sabiscore.git"
  branch: "feat/edge-v3"
  tagline: "Reverse-engineers bookie mistakes and stakes with disciplined sizing."

# Safety / dev notes
# - Keep run_command/test_execution disabled for CI or shared environments.
# - Use absolute paths on Windows; Serena has had issues with relative mounts in containers.
# - If running in Docker, mount the project to the same path inside the container, or
#   update project_root to the container-visible path.

# Example recommended commands (Windows PowerShell):
# 1) Start the MCP server and explicitly set project at start:
#    uvx --from git+https://github.com/oraios/serena.git serena start-mcp-server --project "C:/Users/USR/Documents/SabiScore"
# 2) Force an index (from project root):
#    cd "C:/Users/USR/Documents/SabiScore"; uvx --from git+https://github.com/oraios/serena.git serena project index
# 3) Verify active project via serena CLI (if available):
#    serena project status

# --- End of config ---------------------------------------------------------
