export const LEAGUE_TEAMS = {
  EPL: [
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Brighton",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Ipswich Town",
    "Leicester City",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Southampton",
    "Tottenham Hotspur",
    "West Ham United",
    "Wolverhampton"
  ],
  "La Liga": [
    "Alaves",
    "Athletic Club",
    "Atletico Madrid",
    "Barcelona",
    "Celta Vigo",
    "Elche",
    "Espanyol",
    "Getafe",
    "Girona",
    "Las Palmas",
    "Leganes",
    "Mallorca",
    "Osasuna",
    "Rayo Vallecano",
    "Real Betis",
    "Real Madrid",
    "Real Sociedad",
    "Sevilla",
    "Valencia",
    "Villarreal"
  ],
  "Serie A": [
    "Atalanta",
    "Bologna",
    "Cagliari",
    "Como",
    "Empoli",
    "Fiorentina",
    "Genoa",
    "Inter Milan",
    "Juventus",
    "Lazio",
    "Lecce",
    "Milan",
    "Monza",
    "Napoli",
    "Parma",
    "Roma",
    "Salernitana",
    "Sassuolo",
    "Torino",
    "Udinese"
  ],
  Bundesliga: [
    "Augsburg",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Bochum",
    "Borussia Dortmund",
    "Borussia Monchengladbach",
    "Darmstadt",
    "Eintracht Frankfurt",
    "FC Heidenheim",
    "Freiburg",
    "Hamburg",
    "Hoffenheim",
    "Holstein Kiel",
    "Mainz",
    "RB Leipzig",
    "St. Pauli",
    "Stuttgart",
    "Union Berlin",
    "VfL Wolfsburg",
    "Werder Bremen"
  ],
  "Ligue 1": [
    "Angers",
    "Auxerre",
    "Brest",
    "Clermont",
    "Havre",
    "Lens",
    "Lille",
    "Lorient",
    "Lyon",
    "Marseille",
    "Metz",
    "Monaco",
    "Montpellier",
    "Nantes",
    "Nice",
    "Paris Saint-Germain",
    "Reims",
    "Rennes",
    "Saint-Etienne",
    "Toulouse"
  ]
} as const;

export type LeagueId = keyof typeof LEAGUE_TEAMS;

export function getTeamsForLeague(league: LeagueId): readonly string[] {
  return LEAGUE_TEAMS[league];
}
